runtime: go115
service: randomquotes-go

# APIENDPOINT environment variable points to an external quotes api endpoint
#env_variables:
APIENDPOINT: "https://github.com/OctopusSamples/RandomQuotesAPI-Java-Azure-Functions"
